// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UCMrUAqMafceaEYDER0kSMrSkp8zNbI',
    appId: '1:101875386297:web:2d338b8de5c8f923ced868',
    messagingSenderId: '101875386297',
    projectId: 'movie-app-d074e',
    authDomain: 'movie-app-d074e.firebaseapp.com',
    storageBucket: 'movie-app-d074e.appspot.com',
    measurementId: 'G-2GPNB52WBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rj0smRGb2Ej1eOelZZUWO31o56M6udU',
    appId: '1:101875386297:android:b0d5be5356ca433cced868',
    messagingSenderId: '101875386297',
    projectId: 'movie-app-d074e',
    storageBucket: 'movie-app-d074e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUo153vvqA4wdGnlaJsblj3lVaboIJYxE',
    appId: '1:101875386297:ios:1e73debb71c4773eced868',
    messagingSenderId: '101875386297',
    projectId: 'movie-app-d074e',
    storageBucket: 'movie-app-d074e.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUo153vvqA4wdGnlaJsblj3lVaboIJYxE',
    appId: '1:101875386297:ios:d651503d92e78cf2ced868',
    messagingSenderId: '101875386297',
    projectId: 'movie-app-d074e',
    storageBucket: 'movie-app-d074e.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
